# Generated by Django 4.1.2 on 2022-10-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('position', models.CharField(max_length=1000)),
                ('games_played', models.PositiveIntegerField()),
                ('minutes_played', models.FloatField()),
                ('yellow_cards', models.PositiveIntegerField()),
            ],
        ),
    ]
