# Generated by Django 4.1.2 on 2022-11-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0003_reader'),
    ]

    operations = [
        migrations.AddField(
            model_name='reader',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
