# Generated by Django 4.1.2 on 2022-11-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radar', '0004_reader_file2'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='nm', max_length=200),
        ),
    ]
